<?php 
    define("NOME_SITE", "Meu Site");

    $titulo[] = "Título 1";
    $texto[] = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc congue convallis nibh non tincidunt. Praesent eu felis laoreet, iaculis ipsum nec, convallis diam. Morbi vitae consequat tortor, posuere porttitor nibh. Quisque euismod lectus vel diam scelerisque, porta vulputate lectus tristique. Nunc nec condimentum odio. Aliquam sit amet porta metus. Aenean faucibus velit sit amet cursus efficitur. Donec commodo tellus vel felis fringilla aliquet. Sed cursus dui efficitur magna molestie viverra. Mauris dui tellus, rhoncus id semper ac, suscipit in arcu. Sed sed viverra metus. Nam finibus eu eros eget pharetra. Sed laoreet urna vel est faucibus molestie. Nullam vitae mi libero. Aenean laoreet diam at molestie sodales. Cras facilisis erat a mi elementum feugiat. Nulla interdum odio aliquam, suscipit ipsum at, elementum turpis. Quisque rutrum dolor est, at hendrerit nisl euismod vel. Vestibulum consequat maximus vehicula. In varius scelerisque sapien, nec euismod magna luctus ac. Etiam euismod, libero in ornare auctor, velit quam auctor enim, vitae lacinia quam nisl eget purus. Fusce ornare justo eu posuere porta. Cras eu arcu ut nisi commodo aliquam. Maecenas et mattis magna, quis finibus erat. Quisque rutrum eget libero sed rutrum. Aliquam at orci vel nunc tempus tristique. Curabitur metus urna, commodo eget sodales bibendum, ullamcorper ultrices lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed pretium euismod velit ut elementum. Donec mattis sapien a convallis porta.";
    $img[] = "img001.png";

    $titulo[] = "Título 2";
    $texto[] = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc congue convallis nibh non tincidunt. Praesent eu felis laoreet, iaculis ipsum nec, convallis diam. Morbi vitae consequat tortor, posuere porttitor nibh. Quisque euismod lectus vel diam scelerisque, porta vulputate lectus tristique. Nunc nec condimentum odio. Aliquam sit amet porta metus. Aenean faucibus velit sit amet cursus efficitur. Donec commodo tellus vel felis fringilla aliquet. Sed cursus dui efficitur magna molestie viverra. Mauris dui tellus, rhoncus id semper ac, suscipit in arcu. Sed sed viverra metus. Nam finibus eu eros eget pharetra. Sed laoreet urna vel est faucibus molestie. Nullam vitae mi libero. Aenean laoreet diam at molestie sodales. Cras facilisis erat a mi elementum feugiat. Nulla interdum odio aliquam, suscipit ipsum at, elementum turpis. Quisque rutrum dolor est, at hendrerit nisl euismod vel. Vestibulum consequat maximus vehicula. In varius scelerisque sapien, nec euismod magna luctus ac. Etiam euismod, libero in ornare auctor, velit quam auctor enim, vitae lacinia quam nisl eget purus. Fusce ornare justo eu posuere porta. Cras eu arcu ut nisi commodo aliquam. Maecenas et mattis magna, quis finibus erat. Quisque rutrum eget libero sed rutrum. Aliquam at orci vel nunc tempus tristique. Curabitur metus urna, commodo eget sodales bibendum, ullamcorper ultrices lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed pretium euismod velit ut elementum. Donec mattis sapien a convallis porta.";
    $img[] = "img002.png";

    $titulo[] = "Título 3";
    $texto[] = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc congue convallis nibh non tincidunt. Praesent eu felis laoreet, iaculis ipsum nec, convallis diam. Morbi vitae consequat tortor, posuere porttitor nibh. Quisque euismod lectus vel diam scelerisque, porta vulputate lectus tristique. Nunc nec condimentum odio. Aliquam sit amet porta metus. Aenean faucibus velit sit amet cursus efficitur. Donec commodo tellus vel felis fringilla aliquet. Sed cursus dui efficitur magna molestie viverra. Mauris dui tellus, rhoncus id semper ac, suscipit in arcu. Sed sed viverra metus. Nam finibus eu eros eget pharetra. Sed laoreet urna vel est faucibus molestie. Nullam vitae mi libero. Aenean laoreet diam at molestie sodales. Cras facilisis erat a mi elementum feugiat. Nulla interdum odio aliquam, suscipit ipsum at, elementum turpis. Quisque rutrum dolor est, at hendrerit nisl euismod vel. Vestibulum consequat maximus vehicula. In varius scelerisque sapien, nec euismod magna luctus ac. Etiam euismod, libero in ornare auctor, velit quam auctor enim, vitae lacinia quam nisl eget purus. Fusce ornare justo eu posuere porta. Cras eu arcu ut nisi commodo aliquam. Maecenas et mattis magna, quis finibus erat. Quisque rutrum eget libero sed rutrum. Aliquam at orci vel nunc tempus tristique. Curabitur metus urna, commodo eget sodales bibendum, ullamcorper ultrices lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed pretium euismod velit ut elementum. Donec mattis sapien a convallis porta.";
    $img[] = "img003.png";

    $titulo[] = "Título 4";
    $texto[] = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc congue convallis nibh non tincidunt. Praesent eu felis laoreet, iaculis ipsum nec, convallis diam. Morbi vitae consequat tortor, posuere porttitor nibh. Quisque euismod lectus vel diam scelerisque, porta vulputate lectus tristique. Nunc nec condimentum odio. Aliquam sit amet porta metus. Aenean faucibus velit sit amet cursus efficitur. Donec commodo tellus vel felis fringilla aliquet. Sed cursus dui efficitur magna molestie viverra. Mauris dui tellus, rhoncus id semper ac, suscipit in arcu. Sed sed viverra metus. Nam finibus eu eros eget pharetra. Sed laoreet urna vel est faucibus molestie. Nullam vitae mi libero. Aenean laoreet diam at molestie sodales. Cras facilisis erat a mi elementum feugiat. Nulla interdum odio aliquam, suscipit ipsum at, elementum turpis. Quisque rutrum dolor est, at hendrerit nisl euismod vel. Vestibulum consequat maximus vehicula. In varius scelerisque sapien, nec euismod magna luctus ac. Etiam euismod, libero in ornare auctor, velit quam auctor enim, vitae lacinia quam nisl eget purus. Fusce ornare justo eu posuere porta. Cras eu arcu ut nisi commodo aliquam. Maecenas et mattis magna, quis finibus erat. Quisque rutrum eget libero sed rutrum. Aliquam at orci vel nunc tempus tristique. Curabitur metus urna, commodo eget sodales bibendum, ullamcorper ultrices lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed pretium euismod velit ut elementum. Donec mattis sapien a convallis porta.";
    $img[] = "img004.png";

    $titulo[] = "Título 5";
    $texto[] = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc congue convallis nibh non tincidunt. Praesent eu felis laoreet, iaculis ipsum nec, convallis diam. Morbi vitae consequat tortor, posuere porttitor nibh. Quisque euismod lectus vel diam scelerisque, porta vulputate lectus tristique. Nunc nec condimentum odio. Aliquam sit amet porta metus. Aenean faucibus velit sit amet cursus efficitur. Donec commodo tellus vel felis fringilla aliquet. Sed cursus dui efficitur magna molestie viverra. Mauris dui tellus, rhoncus id semper ac, suscipit in arcu. Sed sed viverra metus. Nam finibus eu eros eget pharetra. Sed laoreet urna vel est faucibus molestie. Nullam vitae mi libero. Aenean laoreet diam at molestie sodales. Cras facilisis erat a mi elementum feugiat. Nulla interdum odio aliquam, suscipit ipsum at, elementum turpis. Quisque rutrum dolor est, at hendrerit nisl euismod vel. Vestibulum consequat maximus vehicula. In varius scelerisque sapien, nec euismod magna luctus ac. Etiam euismod, libero in ornare auctor, velit quam auctor enim, vitae lacinia quam nisl eget purus. Fusce ornare justo eu posuere porta. Cras eu arcu ut nisi commodo aliquam. Maecenas et mattis magna, quis finibus erat. Quisque rutrum eget libero sed rutrum. Aliquam at orci vel nunc tempus tristique. Curabitur metus urna, commodo eget sodales bibendum, ullamcorper ultrices lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed pretium euismod velit ut elementum. Donec mattis sapien a convallis porta.";
    $img[] = "img001.png";

    $titulo[] = "Título 6";
    $texto[] = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc congue convallis nibh non tincidunt. Praesent eu felis laoreet, iaculis ipsum nec, convallis diam. Morbi vitae consequat tortor, posuere porttitor nibh. Quisque euismod lectus vel diam scelerisque, porta vulputate lectus tristique. Nunc nec condimentum odio. Aliquam sit amet porta metus. Aenean faucibus velit sit amet cursus efficitur. Donec commodo tellus vel felis fringilla aliquet. Sed cursus dui efficitur magna molestie viverra. Mauris dui tellus, rhoncus id semper ac, suscipit in arcu. Sed sed viverra metus. Nam finibus eu eros eget pharetra. Sed laoreet urna vel est faucibus molestie. Nullam vitae mi libero. Aenean laoreet diam at molestie sodales. Cras facilisis erat a mi elementum feugiat. Nulla interdum odio aliquam, suscipit ipsum at, elementum turpis. Quisque rutrum dolor est, at hendrerit nisl euismod vel. Vestibulum consequat maximus vehicula. In varius scelerisque sapien, nec euismod magna luctus ac. Etiam euismod, libero in ornare auctor, velit quam auctor enim, vitae lacinia quam nisl eget purus. Fusce ornare justo eu posuere porta. Cras eu arcu ut nisi commodo aliquam. Maecenas et mattis magna, quis finibus erat. Quisque rutrum eget libero sed rutrum. Aliquam at orci vel nunc tempus tristique. Curabitur metus urna, commodo eget sodales bibendum, ullamcorper ultrices lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed pretium euismod velit ut elementum. Donec mattis sapien a convallis porta.";
    $img[] = "img002.png";

    $titulo[] = "Título 7";
    $texto[] = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc congue convallis nibh non tincidunt. Praesent eu felis laoreet, iaculis ipsum nec, convallis diam. Morbi vitae consequat tortor, posuere porttitor nibh. Quisque euismod lectus vel diam scelerisque, porta vulputate lectus tristique. Nunc nec condimentum odio. Aliquam sit amet porta metus. Aenean faucibus velit sit amet cursus efficitur. Donec commodo tellus vel felis fringilla aliquet. Sed cursus dui efficitur magna molestie viverra. Mauris dui tellus, rhoncus id semper ac, suscipit in arcu. Sed sed viverra metus. Nam finibus eu eros eget pharetra. Sed laoreet urna vel est faucibus molestie. Nullam vitae mi libero. Aenean laoreet diam at molestie sodales. Cras facilisis erat a mi elementum feugiat. Nulla interdum odio aliquam, suscipit ipsum at, elementum turpis. Quisque rutrum dolor est, at hendrerit nisl euismod vel. Vestibulum consequat maximus vehicula. In varius scelerisque sapien, nec euismod magna luctus ac. Etiam euismod, libero in ornare auctor, velit quam auctor enim, vitae lacinia quam nisl eget purus. Fusce ornare justo eu posuere porta. Cras eu arcu ut nisi commodo aliquam. Maecenas et mattis magna, quis finibus erat. Quisque rutrum eget libero sed rutrum. Aliquam at orci vel nunc tempus tristique. Curabitur metus urna, commodo eget sodales bibendum, ullamcorper ultrices lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed pretium euismod velit ut elementum. Donec mattis sapien a convallis porta.";
    $img[] = "img003.png";

    function converterPalavras($valor, $qtd) {
        $p = explode(" ", $valor);
        $txt = "";
        if(count($p) > $qtd) {
            for($j = 0; $j < $qtd; $j++) {
                $txt .= " " . $p[$j];
            }
        } else {
            $txt = $texto[$i];
        }
        $txt = trim($txt);
        return $txt;
    }
?>